dist: xenial
language: java
jdk: openjdk11
python: 3.7
install:
  - sudo apt-get update
  - sudo apt-get install -y python3-pip
  - sudo pip3 install --no-cache-dir pipenv
  - cd scripts # switch to scripts directory
  - pipenv sync
script:
  - pipenv run python changelog.py
  - cd .. # switch back to parent directory
  - ./gradlew build
deploy:
  - provider: releases
    api_key: $GITHUB_AUTH_TOKEN
    file_glob: true
    file: build/libs/*.jar
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: ./gradlew publishPlugin
    skip_cleanup: true
    on:
      tags: true
