# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - master
  tags:
    include:
      - v1.*

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
    displayName: 'Setup Python'

  - script: pip install pipenv
    displayName: 'Install pipenv'

  - script: pipenv lock -r > requirements.txt
    workingDirectory: 'scripts'
    displayName: 'Create requirements.txt from Pipfile'

  - script: pip install -r requirements.txt
    workingDirectory: 'scripts'
    displayName: 'Install requirements.txt'

  - script: python build.py
    workingDirectory: 'scripts'
    displayName: 'Generate release note and plugin description'

  - task: Gradle@2
    inputs:
      jdkVersionOption: '1.11'
      gradleOptions: '-Xmx1024m'
      tasks: 'build'
    displayName: 'Build plugin'

  - task: GitHubRelease@0
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
    inputs:
      gitHubConnection: 'GitHub Release'
      repositoryName: '$(Build.Repository.Name)'
      action: 'create'
      assets: 'build/libs/*.jar'
      assetUploadMode: 'delete'
      tagSource: 'auto'
      target: '$(Build.SourceVersion)'
    displayName: 'Publish to GitHub Release'

  - task: Gradle@2
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
    inputs:
      jdkVersionOption: '1.11'
      options: '-Djetbrains.username=$(jetbrains.username) -Djetbrains.token=$(jetbrains.token)'
      gradleOptions: '-Xmx1024m'
      tasks: 'publishPlugin'
    displayName: 'Publish to JetBrains Plugin Repository'